// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmudipqtcmmzwzqkhree.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdWRpcHF0Y21tend6cWtocmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzc1MzgsImV4cCI6MjA2NTU1MzUzOH0.WrrexV4FA2Z5vnkLqWWLhA9zM1c6QVu_3Ohs9awT2IY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);